"use client";
import {Sprout,LayoutDashboard,Ticket,Clock3,ClipboardList,Bell,ArrowRight,Wheat,UserRound,ShieldCheck,Building2,Users,LogOut,Info,RefreshCw,Languages,Wifi} from "lucide-react";
import Link from "next/link";
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from "@/components/ui/sidebar";
import {Switch} from "@/components/ui/switch";
import {Skeleton} from "@/components/ui/skeleton";
import {Toaster} from "@/components/ui/sonner";
import {MandiProvider,useMandi} from "./mandi-context";
import {Overview,ProfileView,CropsView,BookView,QueueView,BookingsView,NotificationsView,BookingDetail} from "./farmer-views";
import {StaffView,MandisView,PeopleView} from "./staff-views";

const views:Record<string,[string,string]>={overview:["Overview","अवलोकन"],book:["Book a token","टोकन बुक करें"],queue:["Live queue","लाइव कतार"],bookings:["My bookings","मेरी बुकिंग"],crops:["My crops","मेरी फसलें"],notifications:["Notifications","सूचनाएँ"],profile:["My profile","मेरी प्रोफ़ाइल"],staff:["Procurement desk","खरीद डेस्क"],mandis:["Manage mandis","मंडियाँ"],people:["People & verification","लोग और सत्यापन"],about:["Help & information","सहायता और जानकारी"]};
function SideNav(){const {user,identity,t,hi,view,data,lowData,setLowData}=useMandi();const {setOpenMobile}=useSidebar();const nav=(items:[string,typeof Sprout][])=>items.map(([id,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton asChild isActive={view===id} className="nav-item"><Link href={id==="overview"?"/":"/"+id} onClick={()=>setOpenMobile(false)}><Icon/><span>{views[id][hi?1:0]}</span>{id==="notifications"&&data.notifications.some(n=>!n.read_at)&&<span className="notification-count">{data.notifications.filter(n=>!n.read_at).length}</span>}</Link></SidebarMenuButton></SidebarMenuItem>);
 return <Sidebar><SidebarHeader className="brand"><Link href="/" className="brand-link" onClick={()=>setOpenMobile(false)}><span className="brand-mark"><Sprout/></span><div><strong>MandiMitra</strong><small>आपका मंडी साथी</small></div></Link></SidebarHeader><div className="sidebar-account"><span className="avatar">{user?user.name.slice(0,1).toUpperCase():<UserRound size={18}/>}</span><div><strong>{user?.name||t("Welcome to MandiMitra","MandiMitra में आपका स्वागत")}</strong><small>{user?.role==="admin"?t("Administrator","प्रशासक"):user?.role==="staff"?t("Mandi staff","मंडी कर्मचारी"):t("Farmer workspace","किसान कार्यक्षेत्र")}</small></div></div><SidebarContent><div className="nav-label">{t("MY WORKSPACE","मेरा कार्यक्षेत्र")}</div><SidebarMenu>{nav([["overview",LayoutDashboard],["book",Ticket],["queue",Clock3],["bookings",ClipboardList],["crops",Wheat],["notifications",Bell]])}</SidebarMenu>{user&&["admin","staff"].includes(user.role)&&<><div className="nav-label">{t("MANDI OPERATIONS","मंडी संचालन")}</div><SidebarMenu>{nav([["staff",ShieldCheck],["people",Users],...(user.role==="admin"?[["mandis",Building2] as [string,typeof Sprout]]:[])])}</SidebarMenu></>}</SidebarContent><SidebarFooter className="sidebar-bottom"><label className="low-data-control"><Wifi size={16}/><span>{t("Low-data mode","कम डेटा मोड")}</span><Switch aria-label={t("Low-data mode","कम डेटा मोड")} checked={lowData} onCheckedChange={setLowData}/></label><Link className="sidebar-footer-link" href="/profile" onClick={()=>setOpenMobile(false)}><UserRound size={17}/>{t("My profile","मेरी प्रोफ़ाइल")}</Link><Link className="sidebar-footer-link" href="/about" onClick={()=>setOpenMobile(false)}><Info size={17}/>{t("Help & information","सहायता और जानकारी")}</Link>{identity&&<a className="sidebar-footer-link" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={17}/>{t("Sign out","साइन आउट")}</a>}<small className="sidebar-credit">MandiMitra · TechCatalyst</small></SidebarFooter></Sidebar>;
}
function About(){const {t,lowData}=useMandi();return <><div className="page-heading"><div><p className="eyebrow">{t("HELP & INFORMATION","सहायता और जानकारी")}</p><h1>{t("Before your mandi visit","मंडी जाने से पहले")}</h1><p>{t("A few things to know about your token and records.","अपने टोकन और रिकॉर्ड के बारे में आवश्यक बातें।")}</p></div></div><div className="help-grid">{[
 [t("Register, then verify","पंजीकरण, फिर सत्यापन"),t("Complete your profile and choose a verification mandi. Bring the identification and crop documents required by that centre to its staff. Once verified, register a crop lot and reserve an available slot.","प्रोफ़ाइल पूरी करके सत्यापन मंडी चुनें। उस केंद्र के आवश्यक पहचान और फसल दस्तावेज़ कर्मचारियों को दिखाएँ। सत्यापन के बाद फसल जोड़कर खाली स्लॉट बुक करें।")],
 [t("When you arrive","जब आप पहुँचें"),t("Arrive within your reserved slot and show your token to the check-in desk. Staff confirm your arrival. Checked-in farmers are called by slot, then token sequence, as weighing desks become available.","अपने तय स्लॉट में पहुँचकर प्रवेश डेस्क पर टोकन दिखाएँ। कर्मचारी आपका आगमन दर्ज करेंगे। तौल केंद्र खाली होने पर स्लॉट और टोकन क्रम से किसानों को बुलाया जाएगा।")],
 [t("Queue updates & estimates","कतार के अपडेट और अनुमान"),t(`The site refreshes every ${lowData?60:15} seconds while open. Estimates use recent completed procurement durations when enough history exists; otherwise they use the centre’s configured time. Processing delays can change your wait.`, `पेज खुले रहने पर हर ${lowData?60:15} सेकंड में अपडेट होता है। पर्याप्त इतिहास होने पर अनुमान पूरी हुई खरीद के समय पर आधारित होता है, वरना केंद्र के तय समय पर। देरी से इंतज़ार बदल सकता है।`)],
 [t("Payment records","भुगतान रिकॉर्ड"),t("Mandi staff enter accepted weight, the agreed price per kg, and a payment reference after an external payment. MandiMitra does not move money or verify bank settlement. Check your bank account and contact the centre about payment discrepancies.","मंडी कर्मचारी स्वीकृत वजन, तय कीमत और बाहर किए भुगतान का संदर्भ दर्ज करते हैं। MandiMitra पैसे नहीं भेजता और बैंक निपटान की जाँच नहीं करता। बैंक खाता जाँचें और अंतर होने पर केंद्र से संपर्क करें।")],
 [t("Your information","आपकी जानकारी"),t("Your crop and booking records are visible to you and authorised staff. Keep Aadhaar numbers, identity document scans, and bank credentials out of forms and notes. Location is optional and used on your device to compare straight-line distance.","आपकी फसल और बुकिंग आपको और अधिकृत कर्मचारियों को दिखाई देती हैं। फॉर्म में आधार, दस्तावेज़ की तस्वीर या बैंक पासवर्ड न दें। स्थान वैकल्पिक है और आपके डिवाइस पर सीधी दूरी की तुलना के लिए उपयोग होता है।")],
 [t("Participating centres","भागीदार केंद्र"),t("This is an independent procurement management application. A booking applies only to a centre that has joined and is actively operating its queue here. It is not a government procurement approval. Contact your centre for operational help.","यह स्वतंत्र खरीद प्रबंधन ऐप है। बुकिंग केवल उस केंद्र पर लागू है जो यहाँ जुड़ा और सक्रिय है। यह सरकारी खरीद की स्वीकृति नहीं है। संचालन में सहायता के लिए अपने केंद्र से संपर्क करें।")],
 ].map(([title,copy])=><section className="panel" key={title}><h2>{title}</h2><p className="muted">{copy}</p></section>)}</div></>;}
function AppShell(){const {t,hi,setHi,user,identity,view,loading,error,load,market,lowData}=useMandi();const name=views[view]||views.overview;let content;switch(view){case"book":content=<BookView/>;break;case"queue":content=<QueueView/>;break;case"bookings":content=<BookingsView/>;break;case"crops":content=<CropsView/>;break;case"notifications":content=<NotificationsView/>;break;case"profile":content=<ProfileView/>;break;case"staff":content=<StaffView/>;break;case"mandis":content=<MandisView/>;break;case"people":content=<PeopleView/>;break;case"about":content=<About/>;break;default:content=<Overview/>;}
 return <SidebarProvider style={{"--sidebar-width":"248px"} as React.CSSProperties}><a className="skip-link" href="#main-content">{t("Skip to content","मुख्य सामग्री पर जाएँ")}</a><SideNav/><SidebarInset className="min-w-0"><header className="topbar"><div><SidebarTrigger className="md:hidden"/><span>{t("Farmer portal","किसान पोर्टल")}<span className="breadcrumb">/ {name[hi?1:0]}</span></span></div><div className="topbar-actions"><button className="language-button" onClick={()=>setHi(!hi)} aria-label={t("Switch to Hindi","Switch to English")}><Languages size={17}/><span>{hi?"English":"हिन्दी"}</span></button><Link href="/notifications" className="icon-button" aria-label={t("Notifications","सूचनाएँ")}><Bell size={19}/></Link><Link href="/profile" className="top-avatar" aria-label={t("My profile","मेरी प्रोफ़ाइल")}>{user?.name?.slice(0,1).toUpperCase()||<UserRound size={19}/>}</Link></div></header><div className="workspace" id="main-content">{error&&<div className="notice error" role="alert"><Info size={18}/><div><strong>{t("Could not get the latest update","नया अपडेट नहीं मिला")}</strong><p>{error} {t("Any displayed records may be out of date.","दिखाए गए रिकॉर्ड पुराने हो सकते हैं।")}</p></div><button onClick={()=>void load()}><RefreshCw size={16}/>{t("Retry","फिर कोशिश करें")}</button></div>}{loading?<div className="loading-workspace" aria-label={t("Loading your workspace","आपकी जानकारी लोड हो रही है")}><Skeleton className="h-5 w-48 mb-4"/><Skeleton className="h-10 w-3/4 mb-8"/><div className="stats-grid">{[0,1,2,3].map(x=><Skeleton className="h-40 rounded-xl" key={x}/>)}</div><Skeleton className="h-80 rounded-xl"/></div>:content}<footer className="workspace-footer"><span>MandiMitra · {t("Your mandi companion","आपका मंडी साथी")}</span><span>{error?t("Updates paused","अपडेट रुके हैं"):market.updated_at?t("Records connected","रिकॉर्ड जुड़े हैं"):t("Connecting…","जुड़ रहे हैं…")}{lowData?` · ${t("Low-data mode","कम डेटा मोड")}`:""}</span></footer></div></SidebarInset><BookingDetail/><Toaster theme="light" richColors position="top-right"/></SidebarProvider>;
}
export default function MandiApp(){return <MandiProvider><AppShell/></MandiProvider>;}
